services:
  - type: web
    name: dataclean-academy
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2

    runtime: python
    pythonVersion: 3.10.13